### ISSUE TITLE
Add a newline after header

### ISSUE THREAD

**Issue by apriha** [OpenHumans/oh-ancestrydna-source#8]
In the resulting `AncestryDNA-genotyping.txt` file, the first SNP reported immediately follows the header (e.g., `... allele2rs4477212 ...`). To fix, add a newline after writing header to file. Issue seems to be in https://github.com/OpenHumans/oh-ancestrydna-source/blob/f68de23180e8dd538e2d9660e2a4db4fd247bf67/main/celery.py

**Comment by gedankenstuecke** [comment]
Thanks for the report! Do you feel like doing a pull request to fix it? :)

**Comment by apriha** [comment]
Sure, no problem!

**Comment by gedankenstuecke** [comment]
Awesome, thanks!
